version: 0.2

env:
  variables:
    AWS_DEFAULT_REGION: "ap-south-1"
    AWS_ACCOUNT_ID: "887984594710"
    IMAGE_REPO_NAME: "adithya-manual-repo"
    ECS_CONTAINER_NAME: "Adithya-manual-container"

phases:
  pre_build:
    commands:
      - echo "Logging in to Amazon ECR..."
      - REPOSITORY_URI="$AWS_ACCOUNT_ID.dkr.ecr.$AWS_DEFAULT_REGION.amazonaws.com/$IMAGE_REPO_NAME"
      - aws ecr get-login-password --region "$AWS_DEFAULT_REGION" | docker login --username AWS --password-stdin "$AWS_ACCOUNT_ID.dkr.ecr.$AWS_DEFAULT_REGION.amazonaws.com"
      - COMMIT_HASH=$(echo "$CODEBUILD_RESOLVED_SOURCE_VERSION" | cut -c 1-7)
      - IMAGE_TAG=${COMMIT_HASH:=latest}
      - echo "Repository URI is $REPOSITORY_URI"
      - echo "Image tag is $IMAGE_TAG"

  build:
    commands:
      - echo "Build started on $(date)"
      - echo "Building the Ruby on Rails production Docker image..."
      - docker build -t "$IMAGE_REPO_NAME:$IMAGE_TAG" .
      - docker tag "$IMAGE_REPO_NAME:$IMAGE_TAG" "$REPOSITORY_URI:$IMAGE_TAG"
      - docker tag "$IMAGE_REPO_NAME:$IMAGE_TAG" "$REPOSITORY_URI:latest"

  post_build:
    commands:
      - echo "Build completed on $(date)"
      - echo "Pushing Docker images to ECR..."
      - docker push "$REPOSITORY_URI:$IMAGE_TAG"
      - docker push "$REPOSITORY_URI:latest"
      - echo "Creating imagedefinitions.json file for the ECS Service rolling deployment..."
      - printf '[{"name":"%s","imageUri":"%s"}]' "$ECS_CONTAINER_NAME" "$REPOSITORY_URI:$IMAGE_TAG" > imagedefinitions.json
      - cat imagedefinitions.json

artifacts:
  files:
    - imagedefinitions.json
